<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Sales\Block\Adminhtml\Order\View\Items $block
 */
$_order = $block->getOrder() ?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <?php
                $i = 0;
                $columns = $block->getColumns();
                $viewModel = $block->getData('cart_item_customer_view_model');
                $storeId = (int)$_order->getStoreId();

                // GroupOrder: Hide column if module is disabled
                if (!$viewModel || !$viewModel->isEnabled($storeId)) {
                    unset($columns['name_customer_add_to_cart']);
                }

                $lastItemNumber = count($columns) ?>
                <?php foreach ($columns as $columnName => $columnTitle) : ?>
                    <?php $i++; ?>
                    <th class="col-<?= $block->escapeHtmlAttr($columnName) ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"><span><?= $block->escapeHtml($columnTitle) ?></span></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <?php $_items = $block->getItemsCollection();?>
        <?php $i = 0; foreach ($_items as $_item) : ?>
            <?php if ($_item->getParentItem()) :
                continue;
            else :
                $i++;
            endif; ?>
            <tbody class="<?= /* @noEscape */ $i%2 ? 'even' : 'odd' ?>">
                <?= $block->getItemHtml($_item) ?>
                <?= $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
