<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var SmartOSC\GroupOrder\Block\QuoteUrl $block */
$quoteUrl = $block->getQuoteUrl();

$groupOrderToken = $this->getRequest()->getParam('key');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get(\Magento\Customer\Model\Session::class);
$isCustomerLoggedIn = $customerSession->isLoggedIn();
?>

<?php if ($isCustomerLoggedIn) : ?>
    <?php if ($groupOrderToken === null) : ?>
        <button onclick="copyToClipboard('<?= $quoteUrl; ?>')">Initiate A Group Order On This Page.</button>
    <?php endif; ?>
<?php endif; ?>

<script>
    function copyToClipboard(text) {
        let dummy = document.createElement("input");
        document.body.appendChild(dummy);
        dummy.setAttribute("value", text);
        dummy.select();
        document.execCommand("copy");
        document.body.removeChild(dummy);
        alert("Group Order URL copied!");
    }
</script>
