<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**
 * Product list toolbar
 *
 * @var $block \SmartOSC\GroupOrder\Block\QuoteUrl
 */

$helper = $this->helper(\SmartOSC\GroupOrder\Helper\Data::class);
$enable = $helper->isEnabled();
?>
<?php if ($block->getCollection()->getSize()) : ?>
    <?php
    $widgetOptionsJson = $block->getWidgetOptionsJson();
    // Use json_decode directly or inject Serializer into Block if needed.
    // Here we just pass it to data-mage-init.
    ?>
    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm": <?= /* @noEscape */
    $widgetOptionsJson ?>}'>
        <?php if ($block->getIsBottom()): ?>
            <?= $block->getPagerHtml() ?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
        <?php else: ?>
            <?php if ($block->isExpanded()): ?>
                <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
            <?php endif ?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
            <?php if ($block->isExpanded()): ?>
                <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
            <?php endif ?>
            <?php if ($enable) : ?>
                <?= $block->fetchView($block->getTemplateFile('SmartOSC_GroupOrder::toolbar/button.phtml')) ?>
            <?php endif ?>
        <?php endif ?>
    </div>
<?php endif ?>
