<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Magento\Sales\Block\Adminhtml\Items\Column\DefaultColumn $block */ ?>
<?php $_item = $block->getItem() ?>

<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerRepository = $objectManager->get(\Magento\Customer\Api\CustomerRepositoryInterface::class);
    $customer = $customerRepository->getById($_item->getData('customer_id'));
    $name = $customer->getFirstname() . ' ' . $customer->getLastname();
?>

<div>
    <?= /* @noEscape */ $name ?>
</div>
