<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Sales\Block\Adminhtml\Items\Column\DefaultColumn $block */
/** @var \SmartOSC\GroupOrder\ViewModel\CartItemCustomer $viewModel */
?>

<?php
$_item = $block->getItem();
$viewModel = $block->getData('cart_item_customer_view_model');
$customer_id = $_item->getData('customer_id');

$name = '';
$storeId = (int)$_item->getOrder()->getStoreId();
if ($viewModel && $viewModel->isEnabled($storeId) && $customer_id) {
    $name = $viewModel->getCustomerInfo((int)$customer_id, false);
}
?>

<!-- Item ID: <?= $_item->getId() ?> | Customer ID: <?= var_export($customer_id, true) ?> -->
<div>
    <?= $block->escapeHtml($name) ?>
</div>
